// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GitBadge: typeof import('./components/GitBadge.vue')['default']
    IconInfo: typeof import('./components/IconInfo.vue')['default']
    LangSwitcher: typeof import('./components/LangSwitcher.vue')['default']
    Message: typeof import('./components/Message.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RandomIcon: typeof import('./components/RandomIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    ToggleTheme: typeof import('./components/ToggleTheme.vue')['default']
    ToolSidebar: typeof import('./components/ToolSidebar.vue')['default']
  }
}

export {}
